nelmio_api_doc:
    documentation:
        info:
            title: Quai Antique API
            description: Documentation de l'API Quai Antique.
            version: 1.0.0
        components:
            securitySchemes :
                X-AUTH-TOKEN:
                    type : apiKey
                    name: X-AUTH-TOKEN
                    in: header
        security:
            - X-AUTH-TOKEN: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
